<?php

/**
 * ISO 3166-1 alpha-2 country codes with labels.
 * Used for registration, filtering, and dropdowns.
 */
return [
    ['code' => 'SA', 'label' => 'Saudi Arabia'],
    ['code' => 'AE', 'label' => 'United Arab Emirates'],
    ['code' => 'KW', 'label' => 'Kuwait'],
    ['code' => 'QA', 'label' => 'Qatar'],
    ['code' => 'BH', 'label' => 'Bahrain'],
    ['code' => 'OM', 'label' => 'Oman'],
    ['code' => 'EG', 'label' => 'Egypt'],
    ['code' => 'JO', 'label' => 'Jordan'],
    ['code' => 'LB', 'label' => 'Lebanon'],
    ['code' => 'SY', 'label' => 'Syria'],
    ['code' => 'IQ', 'label' => 'Iraq'],
    ['code' => 'YE', 'label' => 'Yemen'],
    ['code' => 'PS', 'label' => 'Palestine'],
    ['code' => 'MA', 'label' => 'Morocco'],
    ['code' => 'DZ', 'label' => 'Algeria'],
    ['code' => 'TN', 'label' => 'Tunisia'],
    ['code' => 'LY', 'label' => 'Libya'],
    ['code' => 'SD', 'label' => 'Sudan'],
    ['code' => 'US', 'label' => 'United States'],
    ['code' => 'GB', 'label' => 'United Kingdom'],
    ['code' => 'CA', 'label' => 'Canada'],
    ['code' => 'AU', 'label' => 'Australia'],
    ['code' => 'DE', 'label' => 'Germany'],
    ['code' => 'FR', 'label' => 'France'],
    ['code' => 'IT', 'label' => 'Italy'],
    ['code' => 'ES', 'label' => 'Spain'],
    ['code' => 'NL', 'label' => 'Netherlands'],
    ['code' => 'BE', 'label' => 'Belgium'],
    ['code' => 'SE', 'label' => 'Sweden'],
    ['code' => 'CH', 'label' => 'Switzerland'],
    ['code' => 'AT', 'label' => 'Austria'],
    ['code' => 'TR', 'label' => 'Turkey'],
    ['code' => 'IN', 'label' => 'India'],
    ['code' => 'PK', 'label' => 'Pakistan'],
    ['code' => 'BD', 'label' => 'Bangladesh'],
    ['code' => 'ID', 'label' => 'Indonesia'],
    ['code' => 'MY', 'label' => 'Malaysia'],
    ['code' => 'SG', 'label' => 'Singapore'],
    ['code' => 'PH', 'label' => 'Philippines'],
    ['code' => 'CN', 'label' => 'China'],
    ['code' => 'JP', 'label' => 'Japan'],
    ['code' => 'KR', 'label' => 'South Korea'],
    ['code' => 'BR', 'label' => 'Brazil'],
    ['code' => 'MX', 'label' => 'Mexico'],
    ['code' => 'AR', 'label' => 'Argentina'],
    ['code' => 'ZA', 'label' => 'South Africa'],
    ['code' => 'NG', 'label' => 'Nigeria'],
    ['code' => 'KE', 'label' => 'Kenya'],
    ['code' => 'AF', 'label' => 'Afghanistan'],
    ['code' => 'AL', 'label' => 'Albania'],
    ['code' => 'IR', 'label' => 'Iran'],
    ['code' => 'IL', 'label' => 'Israel'],
    ['code' => 'RU', 'label' => 'Russia'],
    ['code' => 'UA', 'label' => 'Ukraine'],
    ['code' => 'PL', 'label' => 'Poland'],
    ['code' => 'PT', 'label' => 'Portugal'],
    ['code' => 'GR', 'label' => 'Greece'],
    ['code' => 'CZ', 'label' => 'Czech Republic'],
    ['code' => 'RO', 'label' => 'Romania'],
    ['code' => 'HU', 'label' => 'Hungary'],
    ['code' => 'FI', 'label' => 'Finland'],
    ['code' => 'NO', 'label' => 'Norway'],
    ['code' => 'DK', 'label' => 'Denmark'],
    ['code' => 'IE', 'label' => 'Ireland'],
    ['code' => 'NZ', 'label' => 'New Zealand'],
];
